### PR TITLE
Allow gradle incremental compiling with lombok

### PR DESCRIPTION
**Pull request by pbi-qfs**
Fixes issue #1580

Any recommended way to set up test for this use case?

### CODE REVIEW

**Comment by oehme** [comment]
@pbi-qfs I recommend you write a few end-to-end tests using Gradle's [tooling API](https://docs.gradle.org/current/userguide/embedding.html#sec:embedding_quickstart). The test would

- set up a small example project
- invoke Gradle's `javaCompile` task
- do a small incremental change
- invoke the compile task again
- assert that only the expected files got recompiled

**Comment by oehme** [comment]
Please also note that the registration mechanism will change in Gradle 4.8 to be more flexible and will be based on processor options instead of a META-INF file. The META-INF file will still be supported till 5.0, but no longer work after. See [this](https://github.com/gradle/gradle/pull/5255) pull request in Gradle that I'm going to merge soon.

**Comment by pbi-qfs** [comment]
@oehme: Thanks for the suggestions on testing, gradle incremental is one side of the medal, though. I'm more concerned with the lombok side, so to ensure that all transformations still run through, and I'm not familiar on how to set up tests with different compiling environment inside the test structure of the lombok project.

**Comment by 404hasFound** [comment]
.

**Comment by rzwitserloot** [comment]
Hey @pbi-qfs can you send one more pullreq where you add your name to the AUTHORS file? Thanks!

Excellent work, thanks for the PR!

**Comment by oehme** [comment]
See my comment above, the registration mechanism will change in 4.8 and Gradle 5.0 will ignore the meta-inf file. Can you please adjust Lombok to use the new mechanism instead?

**Comment by pbi-qfs** [comment]
@oehme When my Processor is derived from javax.annotation.processing.AbstractProcessor, it should be sufficient to add @SupportedOptions("org.gradle.annotation.processing.isolating") to the processor, isn't it (as long as no specific getSupportedOptions() implementation exists)?

**Comment by oehme** [comment]
Yes, that'll work as well.

**Comment by pbi-qfs** [comment]
It is the easier approach with less lines of code :)

**Comment by oehme** [comment]
@rzwitserloot Will there be a release with this soon? Just let me know so we can promote it :)

**Pull request merged**
