### PR TITLE
Fix missing parameter names, annotations in following annotation processors

### PR DESCRIPTION
**Pull request by dstepanov**
Fixes https://github.com/micronaut-projects/micronaut-core/issues/1566

### CODE REVIEW

**Comment by Rawi01** [comment]
- I think `savedParameterNames` is not required, `params()` and `getParameters()` returns the `params` field if it is `!= null` and will not read `savedParameterNames`
- `parameterNames` is never used
- To build a new `List`, `ListBuffer` can be used

Disclaimer: I'm not a project owner.

**Comment by dstepanov** [comment]
@Rawi01 Thanks for suggestions!

**Comment by rspilker** [comment]
@dstepanov Can you please add you name to the AUTHORS file, so we are legally covered?

**Comment by dstepanov** [comment]
@rspilker Added

**Comment by dstepanov** [comment]
@rspilker Do you think this PR can make it to the next release?

**Comment by rspilker** [comment]
Yes, Thursday I'll work on getting this in. We do not have a release date yet.

**Comment by Rawi01** [comment]
@dstepanov I noticed a bunch of `NullPointerExcceptions` compiling with this fix, it seems like that `param.sym` can be `null` and the `ListBuffer` does not allow `null` values. I had no time to look into it and figure out why it is `null` sometimes.

**Comment by dstepanov** [comment]
@Rawi01 What are you compiling?

**Comment by Rawi01** [comment]
Should have mentioned that, I noticed it compiling this one: https://github.com/dmuatdbh/lombok (you have to run the ClassGenerator first) using Java 8

**Comment by dstepanov** [comment]
Probably some annotation processor is generating incorrect model. It looks like it needs null check :-/

**Comment by rspilker** [comment]
Last Thursday, I already added the null checks. So if any `param.sym` is null, we now fall back to the old behavior.

But since we don't have tests for this feature, I don't know when this occurs, nor if there is a scenario when it doesn't.

**Pull request merged**
