### PR TITLE
Allow jitpack to build lombok using JDK 9+

### PR DESCRIPTION
**Pull request by mmoayyed**
## Problem

Let lombok build on jitpack.io.

From:
https://jitpack.io/docs/BUILDING/#build-customization

> You can create a jitpack.yml file in the root of your repository and override the build commands:
>
> jdk:
>   -openjdk9

## Current

A sample failing build:
https://jitpack.io/com/github/rzwitserloot/lombok/37434ba0cb/build.log

With current failure:

```
-ensureJdk9:

BUILD FAILED
/home/jitpack/build/build.xml:176: To compile lombok, you need JDK9 or higher; lombok requires this version because it's rather difficult 
to produce lombok builds that are compatible on JDK9 without at least building with JDK9. Sorry about that.
```

## Why

This, once working, should allow access to SNAPSHOT builds of lombok whereby developers can quickly test changes and provided feedback. (Case in point: https://github.com/rzwitserloot/lombok/pull/1718)

## Caveats

I ended up switching the java version insufficiency check to use `java.version` rather than `ant.java.version`. This was done to get around jitpack's behavior:

```
-ensureJdk9:
     [echo] Java version: 1.8
     [echo] Java version: 9.0.4
     [echo] Java version insufficient: true
```

Using the above changes, I was able to successfully build lombok. [Here is a build log](https://jitpack.io/com/github/mmoayyed/lombok/-v1.18.0-gbff1237-99/build.log) that shows the build is successful.

# Usage

See: https://jitpack.io/#rzwitserloot/lombok/-SNAPSHOT

## Maven

```
<repositories>
		<repository>
		    <id>jitpack.io</id>
		    <url>https://jitpack.io</url>
		</repository>
</repositories>
<dependency>
	    <groupId>com.github.rzwitserloot</groupId>
	    <artifactId>lombok</artifactId>
	    <version>-SNAPSHOT</version>
</dependency>
```

## Gradle

```
allprojects {
		repositories {
			...
			maven { url 'https://jitpack.io' }
		}
}
dependencies {
	        implementation 'com.github.rzwitserloot:lombok:-SNAPSHOT'
}
```

### CODE REVIEW

**Comment by rzwitserloot** [comment]
Your messages still include the text 'WIP'; is this now ready to go? your jitpack.yml has some debug messages so I'm guessing no.

**Comment by mmoayyed** [comment]
Thanks for the review. This is ready to go.

**Comment by mmoayyed** [comment]
If you prefer, I can also try to document this capability here: https://projectlombok.org/download-edge but I can't seem to find the page in the GitHub repo.

**Comment by rspilker** [comment]
Done.

**Comment by rspilker** [comment]
The contents of https://projectlombok.org/download-edge is located in /website/templates/_download-edge.html

Updates to this file to document how people can use the snapshot release from maven/gradle are highly appreciated. Please create a separate pull request for that.

**Comment by rspilker** [comment]
I just added the link to the jitpack page, but removed it again since I don't think it will work quite yet. I first want to see a working artifact.

**Comment by rspilker** [comment]
We used our DNS to give better a groupId: https://jitpack.io/#org.projectlombok/lombok/master-SNAPSHOT

**Comment by mmoayyed** [comment]
Thank you for reviewing this. I am a bit unclear as to how this was marked as "Done". I don't see the PR merged; so were the changes committed out of band outside this PR?

**Comment by rspilker** [comment]
I rebased your commit, so GitHub didn't understand that these commits are part of the code base. But if you look at the Lombok commit history, you will find them under your name

**Comment by mmoayyed** [comment]
Thank you. I posted another PR to handle jitpack builds based on JDK 10 and will do another for docs, etc.

**Pull request closed without merging**
