### PR TITLE
ShadowClassLoader is now friendlier to trying to extend lombok.

### PR DESCRIPTION
**Pull request by menaren**
Hi, could you add this in the master branch ? We definitly need to create custom annotations in a separated .jar.

### CODE REVIEW

**Comment by naveenramas** [comment]
Can you please push this to master branch?

**Comment by dkushner** [comment]
Have there been any updates on this fix? Extending Lombok is still quite a pain.

**Comment by rzwitserloot** [comment]
As I've said in a few other pull requests... mea culpa. Reviewing pull requests fell into 'manyana' land sometime in 2016, and then we just sheer forgot about them. Very disrespectful to you and the other PR creators.

We're getting through the backlog now. This looks pretty good! Gimme a few to review this.

**Comment by rzwitserloot** [comment]
Somehow it looks like I'm the only committer on a PR? No idea what happened here. Anyway, integrated.

**Pull request merged**
