### PR TITLE
#1065 added "withPrefix" argument for @Builder

### PR DESCRIPTION
**Pull request by programmerr47**
Hello. According to my question https://github.com/rzwitserloot/lombok/issues/1065 I've wrote base implementation of "withPrefix" argument.
If you have any suggestions or remarks, please, feel free to share with me.

Thank you!

### CODE REVIEW

**Comment by congtrinh** [comment]
@rzwitserloot Any reasons why this shouldnt get merged in?

**Comment by jensim** [comment]
I would LOVE to see this merged to master!.. 

Might I suggest a change of "`withPerfix`" to "`setterMethodPrefix`"? Doesn't that fit the rest of the properties on the annotation? ()
Some javadoc might be nice as well..

**Comment by rspilker** [comment]
`set` is for mutables, `with` is for immutables that return a copy with one modification. Builder is mutable. See #1209 for more discussions.

We do appreciate the time you've put into this.

Unfortunately, that means we're going to not merge this in.

Next time, if you want to prevent disappointment, please contact us before creating a pull request to verify if:
- somebody is already working on it
- we think it is a good idea
- discuss alternatives

**Comment by rspilker** [comment]
Uhm, I might have misread part of the implementation the first time. It is not about `with` vs. `set`, but <any given prefix> vs. none.

That doesn't change the outcome though. I'm not saying that the names for the setters are set in stone, but a per-instance setting sounds a bit weird to me, as well as anything else than nothing or `set`.

So the only thing I can imagine is a boolean config key to use a `set` prefix or none. But I'm not yet convinced that the added benefits are is worth the maintenance time.

**Pull request closed without merging**
