### PR TITLE
Potential solution for issue #1164

### PR DESCRIPTION
**Pull request by jludvice**
* copy Jbds* to Rhds* and replace jbdevstudio to devstudio

### CODE REVIEW

**Comment by jludvice** [comment]
It worked for me on linux, but currently I don't have easy way to test on windows / Mac.

**Comment by jludvice** [comment]
Attaching diff comparsion of `JbdsLocation.java` and `RhdsLocation.java`
```diff
diff --git a/JbdsLocation.java b/RhdsLocation.java
index 81fb526..dbe1812 100644
--- a/JbdsLocation.java
+++ b/RhdsLocation.java
@@ -26,20 +26,20 @@ import java.net.URL;
 
 import lombok.installer.CorruptedIdeLocationException;
 
-public class JbdsLocation extends EclipseLocation {
-       public JbdsLocation(String nameOfLocation, File pathToEclipseIni) throws CorruptedIdeLocationException {
+public class RhdsLocation extends EclipseLocation {
+       public RhdsLocation(String nameOfLocation, File pathToEclipseIni) throws CorruptedIdeLocationException {
                super(nameOfLocation, pathToEclipseIni);
        }
        
        @Override public URL getIdeIcon() {
-               return JbdsLocation.class.getResource("jbds.png");
+               return RhdsLocation.class.getResource("rhds.png");
        }
        
        @Override protected String getIniFileName() {
-               return "jbdevstudio.ini";
+               return "devstudio.ini";
        }
        
        @Override protected String getTypeName() {
-               return "JBoss Developer Studio";
+               return "Red Hat JBoss Developer Studio";
        }
 }
```

and `JbdsLocationProvider.java`  and `RhdsLocationProvider.java`:
```diff
diff --git a/JbdsLocationProvider.java b/RhdsLocationProvider.java
index e6df0e4..008cbf8 100644
--- a/JbdsLocationProvider.java
+++ b/RhdsLocationProvider.java
@@ -34,13 +34,13 @@ import lombok.installer.IdeFinder.OS;
 import org.mangosdk.spi.ProviderFor;
 
 @ProviderFor(IdeLocationProvider.class)
-public class JbdsLocationProvider extends EclipseLocationProvider {
+public class RhdsLocationProvider extends EclipseLocationProvider {
        @Override protected List<String> getEclipseExecutableNames() {
-               return Arrays.asList("jbdevstudio.app", "jbdevstudio.exe", "jbdevstudioc.exe", "jbdevstudio");
+               return Arrays.asList("devstudio.app", "devstudio.exe", "devstudioc.exe", "devstudio");
        }
        
        @Override protected String getIniName() {
-               return "jbdevstudio.ini";
+               return "devstudio.ini";
        }
        
        @Override protected IdeLocation makeLocation(String name, File ini) throws CorruptedIdeLocationException {
@@ -48,22 +48,22 @@ public class JbdsLocationProvider extends EclipseLocationProvider {
        }
        
        @Override protected String getMacAppName() {
-               return "jbdevstudio.app";
+               return "devstudio.app";
        }
        
        @Override protected String getUnixAppName() {
-               return "jbdevstudio";
+               return "devstudio";
        }
        
        @Override public Pattern getLocationSelectors(OS os) {
                switch (os) {
                case MAC_OS_X:
-                       return Pattern.compile("^(jbdevstudio|jbdevstudio\\.ini|jbdevstudio\\.app)$", Pattern.CASE_INSENSITIVE);
+                       return Pattern.compile("^(devstudio|devstudio\\.ini|devstudio\\.app)$", Pattern.CASE_INSENSITIVE);
                case WINDOWS:
-                       return Pattern.compile("^(jbdevstudioc?\\.exe|jbdevstudio\\.ini)$", Pattern.CASE_INSENSITIVE);
+                       return Pattern.compile("^(devstudioc?\\.exe|devstudio\\.ini)$", Pattern.CASE_INSENSITIVE);
                default:
                case UNIX:
-                       return Pattern.compile("^(jbdevstudio|jbdevstudio\\.ini)$", Pattern.CASE_INSENSITIVE);
+                       return Pattern.compile("^(devstudio|devstudio\\.ini)$", Pattern.CASE_INSENSITIVE);
                }
        }
 }
```

**Comment by apodhrad** [comment]
I still have a trouble with installing the lombok into RHDS 10.1.0.GA on macosx

**Comment by jludvice** [comment]
@apodhrad RHDS on Mac should be fixed now

**Comment by rspilker** [comment]
Thanks for the contribution

**Pull request merged**
