### PR TITLE
Fix for issues #869 and #1018 - Constructor null check bug when @NonNull with @Accessors

### PR DESCRIPTION
**Pull request by kchirls**
Generates the null check on the constructor parameter instead of the
instance field. Fix for issues #869 and #1018.

### CODE REVIEW

**Comment by kchirls** [comment]
Hi rspilker@ or rzwitserloot@, Do you mind taking a quick look at this? This bug is inconvenient for persons or teams that use a custom variable name prefix style. Thanks!

**Comment by rspilker** [comment]
So far, I've only looked at the source code on Github. The fix itself looks good, although I didn't see the modified after-ecj file, which means that the test for that file will fail.

Also, could you add your name the the AUTORS file so we are legally coverred?

If you cannot get the tests for ecj working or need any other help, please let us know.

**Comment by kchirls** [comment]
ECJ fix and test now included. Name added to AUTHORS file. Changed one of the variables to be final, to account for that case. One minor line change (removing Generated annotation) to account for changes from the latest merge. Let me know if I missed anything. Thanks!

**Comment by kchirls** [comment]
Hi @rspilker. Just a ping that I've made your recommended updates. Thanks!

**Comment by rspilker** [comment]
Thanks a lot! Sorry it took so long to get merged.

**Pull request merged**
