### PR TITLE
 Fix tests under Windows, fix test.javac11 and test.javac14, fix issue #1745

### PR DESCRIPTION
**Pull request by rosti-il**
This also should fix the #1745 issue.

The change of the TestConfiguration.java is based on the fact that
Git for Windows is configured with 'core.autocrlf=true' by default.

### CODE REVIEW

**Comment by rosti-il** [comment]
If you use lombok.maben plugin you must rebuild it with the new version of Lombok.
Just bump its version defined in the lombok.version property:
https://github.com/awhitford/lombok.maven/blob/master/pom.xml

**Comment by Rawi01** [comment]
Unfortunatly there already is a PR (#2536) that also fixes this issue. Seems to be important :smile: 
I am courious if both actually solve the problem completly. If I understand the problem correctly there is an additional `\r` at the end. This PR tries to avoid adding that by removing it early on, the other removes it during writing. Not adding them at all is IMHO the better soloution. Have you tried to compile a non CRLF file on windows? Does that work after applying this PR?

Please also add yourself to the AUTHORS file.

Disclaimer: I'm not a project owner.

**Comment by rosti-il** [comment]
> Unfortunatly there already is a PR (#2536) that also fixes this issue. Seems to be important 😄

Why unfortunately? The project owner should just chose a better solution.

> I am courious if both actually solve the problem completly.

My starting point was a failure of several unit tests on Windows. Now all the tests pass on Windows and no expected result was changed by this PR.

> If I understand the problem correctly there is an additional `\r` at the end.

Right. That additional '\r' character reminds after eliminating the '\n' one and this happens only with CRLF files.

> This PR tries to avoid adding that by removing it early on, the other removes it during writing. Not adding them at all is IMHO the better soloution.

`com.sun.tools.javac.main.JavaCompiler#parse(String fileName)` adds them.
I think it would be wrong converting all source code into LF format on all platforms. Each OS has its own newline encoding standard. This is why Git for Windows configures itself with `core.autocrlf=true` by default.

> Have you tried to compile a non CRLF file on windows? Does that work after applying this PR?

The first version of this PR didn't work correctly with such incorrectly formatted files. I've updated this PR with a better solution. Now it works correctly even with such files.

> Please also add yourself to the AUTHORS file.

Done

**Comment by Rawi01** [comment]
In my opinion its always unfortunate when the limited time of contributors is used for the same thing :smile: 

I think my comment about not adding wrong line breaks was not clear enough. What I meant to say was that there are in general two soloutions for the problem, removing the wrong line breaks in the end or do not add them at all. If I remember correctly your first version tried to add only right line breaks and the other PR removd them in `PrettyPrint`. Your new version now uses both soloutions at the same time which should also be fine.

Have you considered using `dc.split("\r?\n")` instead of the buffered reader?

**Comment by rosti-il** [comment]
> Have you considered using `dc.split("\r?\n")` instead of the buffered reader?

Indeed, this (with double backslashes) allows to make shorter and more readable code. Thank you. I remade my PR respectively.

It's better to be coded `dc.split("\\R")` but than it will not work on Java older than Java 8. Should Lombok support such old versions of Java?

**Comment by randakar** [comment]
It still does, so yes.

There are organisations out there still using versions of java as old as
java 6. I still do not understand why anyone would want to develop software
that far behind the times but somehow it's reality.

**Comment by rzwitserloot** [comment]
awesome work, thank you!

**Pull request merged**
