### PR TITLE
Eclipse feature and bundle for the Lombok Agent

### PR DESCRIPTION
**Pull request by jordiboehmelopez**
Provide eclipse artifacts to distribute the Lombok agent without the need of a custom installer:
* feature, to provide a description, licensing and other UI visible information in the eclipse install UI.
* category.xml, to ease access to the Feature in an installer.
* agent bundle, which contains Lombok 1.18.12 and the p2.inf
* p2.inf, required to define the p2 touchpoints to install/uninstall the required entries in the eclipse.ini file.

An exported p2 update site for Eclipse, which was created using this two projects, can be found at:
https://jordiboehmelopez.github.io/lombok-eclipse/

### CODE REVIEW

**Comment by jordiboehmelopez** [comment]
In case this gets accepted, the next step would be to incorporate the step of generating and exporting/publishing of the repository into the automated build.

**Comment by rzwitserloot** [comment]
We had this on our wishlist, just didn't see a good argument to spend time on this at the cost of some more features, and working on whittling away at the open issues. Which makes your PR particularly timely. I think we'll have a look next thursday. Thanks for this, @jordiboehmelopez

**Comment by rspilker** [comment]
Generating the p2 update site _should_ not be a problem if we can host it ourselves.

**Comment by jordiboehmelopez** [comment]
Awesome.  Thanks for looking into this guys!
If you need any help, let me know.

re/ "if we can host it ourselves":
Using GitHub.io delivery, the p2 repository could easily be hosted here (like I did for https://jordiboehmelopez.github.io/lombok-eclipse/ )

**Comment by rzwitserloot** [comment]
@jordiboehmelopez We didn't manage to get any lombok coding done yesterday, but it's top of our list :)

**Comment by rzwitserloot** [comment]
Allright, man this was so easy! – once you know how to do it, of course. Muchos gracias for all the legwork!

I can't, unfortunately, accept the PR; the PR includes a whole bunch of hardcoded data and an entire lombok.jar which would permanently remain in the git repo. I've recreated all the relevant files in an ant task, and added a link so the ant script can deploy to the server.

I've put 1.18.12 (the current live version) on https://projectlombok.org/p2 and this seems to go swimmingly.

Now to figure out how to get it signed, and get it into the marketplace.

To be continued. Is it okay if I credit you in the changelog instead?

**Comment by rzwitserloot** [comment]
See commit 59aa6761115cb912d5223870be348b70e0e9fd9c

**Comment by jordiboehmelopez** [comment]
> Allright, man this was so easy! – once you know how to do it, of course. Muchos gracias for all the legwork!
> 
> I can't, unfortunately, accept the PR; the PR includes a whole bunch of hardcoded data and an entire lombok.jar which would permanently remain in the git repo. I've recreated all the relevant files in an ant task, and added a link so the ant script can deploy to the server.
> 
> I've put 1.18.12 (the current live version) on https://projectlombok.org/p2 and this seems to go swimmingly.
> 
> Now to figure out how to get it signed, and get it into the marketplace.
> 
> To be continued. Is it okay if I credit you in the changelog instead?

Hey @rzwitserloot, sorry for the delayed response - I was out of town.
"credit in the changelog" is fine :) 

To sign your jars, you can follow one of the three provided options on https://help.eclipse.org/2019-12/index.jsp?topic=%2Forg.eclipse.platform.doc.isv%2Fguide%2Fbundle_security.html

I assume you followed https://wiki.eclipse.org/Equinox_p2_Metadata_Generator to headlessly generate the repository?

**Comment by rzwitserloot** [comment]
@jordiboehmelopez I didn't. Thanks for the doc links, lets me move this issue along!

**Comment by rzwitserloot** [comment]
Unfortunately, the links are useless. It explains basic stuff wikipedia can tell you and omits the crucial aspect, and even lies: It says that it helps to 'establish the identity' which only works if the cert chain is trusted. It then says it uses cacerts, which is a lie; most eclipse plugins, as well as a random project I googled for (https://stuff.mit.edu/afs/sipb/project/android/docs/sdk/installing/installing-adt.html in my case) are signed by CN="Eclipse.org Foundation, Inc" - which is not gonna be in cacerts.

cacerts is filled with immoral business practices and letsencrypt. letsencrypt is not designed for this. Eclipse apparently runs their own root cert which they signed with GeoTrust or themselves (I'm not a pro at reading the output of jarsigner unfortunately). The cert is expired and apparently eclipse doesn't care.

I checked my jdk8 install. LetsEncrypt is not in its cacerts. That is its own WTF, but it also means that the majority of eclipse installs out there aren't going to play ball.

I'm not going to fork over a bunch of dough to a dying industry that's going to do crazy things with my certs.

I'm at an impasse, then. I'll try to get the attention of an eclipse dev, I guess?

I don't have time to sort this stuff out. Without help from team eclipse or a contribution I'm aborting the p2 option for now.

**Comment by jordiboehmelopez** [comment]
@rzwitserloot Rainier, I'm curious: Why do you want/require to sign the p2 repository?
I understand what the benefits of singing are, but should the inability to sign the p2 repo prevent the Lombok p2 repository from existing?
Most p2 repos out there are not signed.

**Comment by rzwitserloot** [comment]
After doing some checks on the marketplace, right now it looks like the problem is that team eclipse doesn't understand how security works. That's sad. "Fortunately", that means all eclipse users are trained to ignore the security warnings and just mindlessly click yes, not understanding what that implies.

The upshot is that we can publish this, completely unsigned. Follow the lemmings off the cliff.

It's there, and has been for a while, so I'm closing the PR. But, we really should improve our documentation on this and consider changing the installer to just explain how to install via the p2 repo. I just updated the docs, the website will pick up this update when we do our next release (real soon now).

**Pull request closed without merging**
