### PR TITLE
Fix NetBeans 8.x compile-on-save issue.

### LINKED ISSUE #1577: Netbeans 8.x compile on save not working with lombok 1.16.20
During debugging of my application I'm used to use hot code replace.
This feature of netbeans allows to replace code on a running jvm.
To make it work you have to enable "compile on save".
So, with lombok 1.16.18 all is working good but with the new version 1.16.20, the hot code replace feature doesn't work.
I can see that my compiled class are removed from the target folder when hitting the save button (I'm working with maven).

### PR DESCRIPTION
**Pull request by charphi**
Fix #1577

### CODE REVIEW

**Comment by md-5** [comment]
Cool!

Going to bed now, but I develop with NetBeans 8.1 and am trying to migrate to NetBeans 9, so I will test both of these platforms tomorrow.

Cheers

**Comment by md-5** [comment]
Works in NetBeans 8.1 (JDK8) and NetBean 9 (JDK10).
:+1:

**Comment by rspilker** [comment]
Can you please add your name to the AUTHORS file at the appropriate location? Then we are legally covered.

**Comment by rspilker** [comment]
Done.

**Comment by md-5** [comment]
Thanks!

**Comment by charphi** [comment]
Thanks

**Pull request merged**
