### PR TITLE
Allow jitpack to use JDK 10 when building lombok

### PR DESCRIPTION
**Pull request by mmoayyed**
Subsequent to #1780 

Sample build outcome:
https://jitpack.io/com/github/mmoayyed/lombok/jitpack11-v1.18.0-gcf9f25a-152/build.log

### CODE REVIEW

**Comment by rspilker** [comment]
The last line is `No build artifacts found`. But I expect that we can instruct jitpack to rin `ant install-maven` instead ant that that would solve the problem. Is that correct?

**Comment by mmoayyed** [comment]
We surely could yes, but that bit is very strange. It looks to me as if, once the artifact is built, jitpack is trying to get it installed in _their own_ local repository and is looking for a pom.xml to do that. 

I'll tweak the build command to see if it can use the new ant command.

**Comment by rspilker** [comment]
I merged it to get the jdk10 in.

**Comment by rspilker** [comment]
FYI, jitpack is too unreliable and slow. In the meantime, and as a result of the lessons learned from trying to get jitpack to work, we have decided to host the snapshot releases on our own website.

Thanks for helping us get to that stage.

**Comment by rspilker** [comment]
https://projectlombok.org/download-edge
You may need a reload to get the latest css, fixing alignment problems of the maven/gradle examples.

**Comment by mmoayyed** [comment]
That is excellent. Thank you for taking care of this.

**Pull request merged**
