### PR TITLE
Use MethodHandler instead of reflective defineClass

### LINKED ISSUE #2810: [BUG] Unhandled event loop exception in Eclipse
After updating Eclipse to use Java 16, building projects gives an error.

1. Install Lombok 1.18.20 in Eclipse, either through the update site or the jar (I tried both).
2. If you used the update site, you will see in installation details: `Lombok 1.18.20 org.projectlombok.feature.feature.group`
3. Create a new Java project and try to create a new class.

The error log will show:

Plugin: org.eclipse.ui

Message: Unhandled event loop exception

Stack trace:
```
java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @5d9618f2
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
	at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.overrideLoadResult(ModuleClassLoader.java:86)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	at org.eclipse.jdt.internal.compiler.parser.Parser.endParse(Parser.java:11732)
	at org.eclipse.jdt.internal.core.util.CommentRecorderParser.endParse(CommentRecorderParser.java:135)
	at org.eclipse.jdt.internal.compiler.parser.Parser.parse(Parser.java:12925)
	at org.eclipse.jdt.internal.compiler.parser.Parser.parse(Parser.java:13149)
	at org.eclipse.jdt.internal.compiler.parser.Parser.parse(Parser.java:13106)
	at org.eclipse.jdt.internal.compiler.parser.Parser.dietParse(Parser.java:11503)
	at org.eclipse.jdt.core.dom.CompilationUnitResolver.parse(CompilationUnitResolver.java:538)
	at org.eclipse.jdt.core.dom.ASTParser.internalCreateAST(ASTParser.java:1224)
	at org.eclipse.jdt.core.dom.ASTParser.createAST(ASTParser.java:820)
	at org.eclipse.jdt.internal.corext.refactoring.TypeContextChecker.parseSuperType(TypeContextChecker.java:771)
	at org.eclipse.jdt.internal.corext.refactoring.TypeContextChecker.parseSuperClass(TypeContextChecker.java:746)
	at org.eclipse.jdt.ui.wizards.NewTypeWizardPage.superClassChanged(NewTypeWizardPage.java:1948)
	at org.eclipse.jdt.ui.wizards.NewTypeWizardPage.typePageDialogFieldChanged(NewTypeWizardPage.java:1232)
	at org.eclipse.jdt.ui.wizards.NewTypeWizardPage.access$2(NewTypeWizardPage.java:1196)
	at org.eclipse.jdt.ui.wizards.NewTypeWizardPage$TypeFieldsAdapter.dialogFieldChanged(NewTypeWizardPage.java:1131)
	at org.eclipse.jdt.internal.ui.wizards.dialogfields.DialogField.dialogFieldChanged(DialogField.java:78)
	at org.eclipse.jdt.internal.ui.wizards.dialogfields.StringDialogField.setText(StringDialogField.java:195)
	at org.eclipse.jdt.ui.wizards.NewTypeWizardPage.setSuperClass(NewTypeWizardPage.java:1480)
	at org.eclipse.jdt.ui.wizards.NewTypeWizardPage.initTypePage(NewTypeWizardPage.java:647)
	at org.eclipse.jdt.ui.wizards.NewClassWizardPage.init(NewClassWizardPage.java:94)
	at org.eclipse.jdt.internal.ui.wizards.NewClassCreationWizard.addPages(NewClassCreationWizard.java:56)
	at org.eclipse.jface.wizard.WizardDialog.createContents(WizardDialog.java:632)
	at org.eclipse.jface.window.Window.create(Window.java:431)
	at org.eclipse.jface.dialogs.Dialog.create(Dialog.java:1094)
	at org.eclipse.ui.internal.actions.NewWizardShortcutAction.run(NewWizardShortcutAction.java:119)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:474)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:580)
	at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:414)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4209)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1043)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4026)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3626)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1157)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1461)
```

Session data:
eclipse.buildId=4.19.0.I20210303-1800
java.version=16
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Command-line arguments:  -os win32 -ws win32 -arch x86_64

In addition, Lombok does not show as installed in the "About Eclipse" window. This was mentioned also in https://github.com/rzwitserloot/lombok/issues/2617.

### PR DESCRIPTION
**Pull request by Rawi01**
This PR fixes #2810 

Since Java 16 reflective access to `ClassLoader.defineClass` is no longer permitted. The recommended solution is to use `MethodHandles.lookup().defineClass` which is useless here because it is limited to classes in the same package. Fortunately the relvant code gets transplanted into a `ClassLoader` and we can call the parent method using a `MethodHandle`.

### CODE REVIEW

**Comment by rzwitserloot** [comment]
I wonder if we're better off making an inner class with the 'normal' (non-reflective) code. I'll look at it in a bit.

**Comment by Rawi01** [comment]
@rzwitserloot The class is limited to Java 4, that's why I used reflection.

**Comment by rzwitserloot** [comment]
.. and involving inner classes in order to avoid classload errors goes exactly against the grain of what transplant is attempting to accomplish. Maybe we can improve on the reflection access but for now using reflection to do this seems like the right strategy.

**Comment by Rawi01** [comment]
It would be great if there would be a way to just write the call to the private/protected method directly without reflection. For example we add a `protected static Class defineClass` in `EclipseLoaderTransplants` and if we call transplant the patcher detects that and replaces the static call with an normal method invocation.

**Pull request merged**
