### PR TITLE
support custom annotation again

### PR DESCRIPTION
**Pull request by liudongmiao**
Since 1.16.X, lombok introduces `ShadowClassLoader`, which breaks custom annotation.
After digging into the codes, it's related to `inOwnBase`.
`InOwnBase` rejects any class not in `lombok.jar`, so it doesn't support custom annotation.

IMO, it's safe to use `!isSystemResource` instead of `inOwnBase`.

### CODE REVIEW

**Comment by rzwitserloot** [comment]
I'm pretty sure isSystemResource is not actually safe here; the whole point of not trying to load 'foreign' classes into our loader is to avoid tainting such classes with the deps of lombok itself.

I've come up with an alternate strategy; check out branch sclExpansionUpdate; the trick here is:

Your classpath root with the lombok extension must contain META-INF/ShadowClassLoader which is a text file that contains the string 'lombok'. Do that, and the shadowclassloader will treat your classpath root the same as its own root (that is, will load anything in there into the lombok space so that lombok can see it, and it can see lombok).

Let me know if this works for you so it can be merged into master.

**Comment by liudongmiao** [comment]
Yes, it works.

For the lombok extension, there are `META-INF/services/lombok.javac.JavacAnnotationHandler` or `META-INF/services/lombok.eclipse.EclipseAnnotationHandler`. IMO, it should be sufficient for the lombok extension without `META-INF/ShadowClassLoader`.

However, I don't know `tainting`. Is it the same with `Sealed`? http://docs.oracle.com/javase/tutorial/deployment/jar/sealman.html

**Comment by liudongmiao** [comment]
I have another idea.

When `SpiLoadUtil` find services, add the resource to `ShadowClassLoader`, however, it's ugly.

**Comment by menaren** [comment]
Hi, when will the sclExpansionUpdate branch modifications be added to the master branch ? 
I wrote a bunch custom annotations for the 1.14.8 which are not working anymore.

**Pull request closed without merging**
