### PR TITLE
Add information about 2020.3 having Lombok support

### PR DESCRIPTION
**Pull request by mjaggard**
Built in support is now available in IntelliJ

### CODE REVIEW

**Comment by rzwitserloot** [comment]
Wait... what? I mean, you're right, but, wait.. what???
 Um, I guess a sizable chunk of tonight's lombok meeting will discuss this :)

**Comment by mkurz** [comment]
Starting with Intellij 2020.3 the lombok-intellij-plugin (https://github.com/mplushnikov/lombok-intellij-plugin) is now bundled with IntelliJ **Ultimate** edition, but _not_ with the Community edition.

**Comment by mkurz** [comment]
Actually maybe I am wrong and it is also bundled with the Community edition....

**Comment by mjaggard** [comment]
I've just changed jobs and this is going to help me a lot with persuading
my new team to use Lombok. Although the other choice is to move over to
Kotlin so I'm actually not too worried about it. :-)

**Pull request merged**
