### PR TITLE
[fix] Fix intellij build with jdk10 (#1572)

### PR DESCRIPTION
**Pull request by tmurakam**
Add a JavaFileManager class name to KNOWN_JAVA9_FILE_MANAGERS,
for IntelliJ build with JDK10.

### CODE REVIEW

**Comment by arvindkumarc** [comment]
Why is this PR still unaccepted?

**Comment by AnthonyWhitakerJr** [comment]
Does this fix compatibility with IntelliJ 2018 RC?

**Comment by wreulicke** [comment]
@rspilker Could you review this PR? 
I hope that this PR will be merge and released.

**Comment by rzwitserloot** [comment]
@arvindkumarc Because lombok is a labour of love. If you expect 2-day turnarounds, you may want to donate or buy a lombok license.

**Comment by jasonCodesAway** [comment]
@rzwitserloot I didn't realize you could become a patron...lombok rocks and I'm happy to pledge my support! You guys light a fire under Oracle's backside to make Java sexy!

**Comment by algotradersxyz** [comment]
Please merge this. My code is breaking with Java 10.

**Pull request merged**
