### PR TITLE
Patch for renaming fields with Getter/Setter/Data in eclipse #210

### PR DESCRIPTION
**Pull request by rgra**
Patches the bytecode of RenameFieldProcessor and removes all methods marked with @Generated from the search results to avoid eclipse refactoring them.

Fixes Issue #210

### CODE REVIEW

**Comment by rspilker** [comment]
Wow, sorry I missed this. I'll look into this soon!

**Comment by jdlaroche** [comment]
Do you plan to merge this soon?

**Comment by rspilker** [comment]
@rgra Can you please add your name the the AUTHORS file, so we are legally covered?

**Comment by rgra** [comment]
@rspilker Done!

**Comment by spiegelm** [comment]
Any chances that this PR will be merged?

**Comment by rspilker** [comment]
Yes :smile:

**Comment by aditya-cap** [comment]
does the latest jar include these changes?

**Comment by rspilker** [comment]
Yes

**Pull request merged**
