### PR TITLE
Fixed @SuperBuilder with generic with inner static class produces CE

### PR DESCRIPTION
**Pull request by Lekanich**
#2262 
Added ability to process JCField as a type parameter for HandleSuperBuilder. javac.

### CODE REVIEW

**Comment by Lekanich** [comment]
It can also fix issue #2278

**Comment by rzwitserloot** [comment]
Nice! Can you add your name to the AUTHORS file as well in this PR?

**Comment by Lekanich** [comment]
Yes, I'll do it.

**Comment by kevinhwang** [comment]
@rzwitserloot Can you guys build a release out of this? Need this functionality from Lombok. :)

**Pull request merged**
