### PR TITLE
added supporing for @val variables inside lambdas.

### PR DESCRIPTION
**Pull request by bulgakovalexander**

### CODE REVIEW

**Comment by rspilker** [comment]
Thanks for the code!

Can you add your name and email address to the AUTHORS file so we are legally covered?

**Comment by bulgakovalexander** [comment]
Hi, @rspilker.
> Can you add your name and email address to the AUTHORS file so we are legally covered?

Done.

**Comment by rspilker** [comment]
I've merged in your modifications after adding a cache for the getBody method.

Thanks for adding the tests as well.

**Comment by rikoe** [comment]
Hi. When is this planned for release, would be really nice to have? The latest edge release was in July, and edge releases aren't in the maven repo anyway, as far as I can tell.

**Pull request closed without merging**
